spring:
  application.name: payments

  event:
    publisher:
      ordersSns: "orders-sns.fifo"
      inventorySns: "inventory-sns.fifo"

aws-resources:
  ordersTopicPaymentsServiceSqs: orders_topic_payment_service.fifo

---
spring:
  config:
    activate:
      on-profile: ["docker"]
  cloud:
    aws:
      region:
        static: "eu-central-1"
      endpoint: "http://localstack:4566"
      credentials:
        access-key: "local_access_key"
        secret-key: "local_secret_key"
aws-resources:
  ordersTopicPaymentsServiceSqs: "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/orders_topic_payment_service.fifo"
