spring:
  application.name: inventory

  db:
    name: "inventory"
    host: localhost
    username: postgres
    password: password

  datasource:
    url: "jdbc:postgresql://${spring.db.host}:5432/${spring.db.name}"
    username: ${spring.db.username}
    password: ${spring.db.password}
  sql:
    init:
      platform: postgresql

  flyway:
    enabled: true
    url: "jdbc:postgresql://${spring.db.host}:5432/${spring.db.name}"
    user: ${spring.db.username}
    password: ${spring.db.password}

aws-resources:
  ordersTopicInventoryServiceSqs: orders_topic_inventory_service.fifo

---
spring:
  config:
    activate:
      on-profile: ["test"]
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: ["docker"]
  cloud:
    aws:
      endpoint: "http://localstack:4566"
aws-resources:
  inventoryServiceEventsQueueUrl: "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/orders_topic_inventory_service.fifo"
